-- Run this file in Supabase SQL Editor before switching the application data provider.
-- The server should use the Supabase service-role key for trusted API operations.

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name varchar(150) not null,
  email varchar(190) not null unique,
  password_hash char(64) not null,
  role varchar(10) not null default 'user' check (role in ('admin', 'bhw', 'user')),
  designation varchar(120),
  assigned_area varchar(120),
  resident_address text,
  contact_number varchar(40),
  residency_confirmed boolean not null default false,
  verification_status varchar(10) not null default 'pending' check (verification_status in ('pending', 'approved', 'rejected')),
  id_document_name varchar(255),
  id_document_type varchar(100),
  id_document_data text,
  created_at timestamptz not null default now()
);

-- Demo administrator account for initial access.
-- Credentials: admin@nutritrack.gov.ph / admin123
insert into public.users (name, email, password_hash, role, designation, residency_confirmed, verification_status)
values (
  'System Admin',
  'admin@nutritrack.gov.ph',
  '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
  'admin',
  'System Administrator',
  false,
  'approved'
)
on conflict (email) do nothing;

create table if not exists public.children (
  id varchar(64) primary key,
  first_name varchar(100) not null,
  middle_name varchar(100),
  last_name varchar(100) not null,
  name varchar(220) not null,
  birth_date date not null,
  age integer not null default 0,
  age_display varchar(80) not null,
  gender varchar(10) not null check (gender in ('Male', 'Female')),
  weight numeric(6,2) not null,
  height numeric(6,2) not null,
  bmi numeric(5,2) not null,
  status varchar(12) not null check (status in ('Normal', 'Underweight', 'Overweight', 'Stunted')),
  avatar varchar(12) not null,
  parent_name varchar(150) not null,
  guardian_type varchar(20),
  mother_name varchar(150) not null,
  father_name varchar(150) not null,
  parent_address text,
  guardian_purok varchar(120),
  guardian_hacienda varchar(120),
  guardian_street varchar(160),
  guardian_barangay varchar(120),
  guardian_city_municipality varchar(120),
  guardian_province varchar(120),
  assigned_area varchar(120),
  assigned_bhw_name varchar(150),
  assigned_bhw_email varchar(190),
  allergies text,
  created_by_email varchar(190),
  updated_at varchar(10),
  created_at timestamptz not null default now()
);

create table if not exists public.meal_entries (
  id varchar(64) primary key,
  child_id varchar(64) not null references public.children(id) on delete cascade,
  date_value date not null,
  meal_type varchar(10) not null check (meal_type in ('Breakfast', 'Lunch', 'Dinner', 'Snack')),
  foods jsonb not null,
  calories integer not null,
  protein numeric(6,2) not null,
  carbs numeric(6,2) not null,
  fat numeric(6,2) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.growth_records (
  id bigint generated by default as identity primary key,
  child_id varchar(64) not null references public.children(id) on delete cascade,
  date_value varchar(10) not null,
  weight numeric(6,2) not null,
  height numeric(6,2) not null,
  created_at timestamptz not null default now()
);

create table if not exists public.nutrition_action_plans (
  child_id varchar(64) primary key references public.children(id) on delete cascade,
  severity varchar(20) not null check (severity in ('Information', 'Monitor', 'Priority follow-up')),
  summary text not null,
  recommendations jsonb not null,
  follow_up_date date not null,
  target_summary text not null,
  bhw_notes text,
  completed_at date,
  created_by_email varchar(190),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users enable row level security;
alter table public.children enable row level security;
alter table public.meal_entries enable row level security;
alter table public.growth_records enable row level security;
alter table public.nutrition_action_plans enable row level security;
